restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=sm-{rule}-{wildcards}
    --partition=wraylab
    --nodelist=dcc-rescomp-29
    --account=wraylab
default-resources:
  - mem_mb=2000
cluster-status: "status-sacct.sh"
max-jobs-per-second: 50
max-status-checks-per-second: 10
local-cores: 2
latency-wait: 60
