name: escapevariants
channels:
  - bioconda
  - conda-forge
dependencies:
  - seqtk=1.3
  - pangolin=3.0.3
  - gatk4=4.1.3.0
  - trim-galore=0.6.5
  - bcftools=1.10.2
  - bedtools=2.25.0
  - bwa=0.7.12
  - perl=5.32.0
  - cutadapt=2.3
  - picard=2.25.0
  - samtools=1.10
  - tabix=0.2.6
  - pandas=1.2.3
  - xlsxwriter=1.3.8
